<section class="image-gallery">
	<div class="gallery-wrapper">
		<ul class="photo-grid" id="poster-grid">
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-kevin-tong.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-kevin-tong.jpg"><div class="photo-caption">Kevin Tong</div></a></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-jay-ryan.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-jay-ryan.jpg"></a><div class="photo-caption">Jay Ryan</div></li>			
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr12/npr-12-james-weinberg.jpg"><img class="photo-grid-img" src="_img/npr12/npr-2012-james-weinberg.jpg"></a><div class="photo-caption">James Weinberg</div></li>					
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-vahalla.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-vahalla.jpg"></a><div class="photo-caption">Vahalla Studios</div></li>				
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-doe-eyed.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-doe-eyed.jpg"></a><div class="photo-caption">Doe Eyed</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-dan-mccarthy.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-dan-mccarthy.jpg"><div class="photo-caption">Dan McCarthy</div></a></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-dkng.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-dkng.jpg"><div class="photo-caption">DKNG/div></a></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-aaron-draplin.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-aaron-draplin.jpg"></a><div class="photo-caption">Aaron Draplin</div></li>					
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-burlesque.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-burlesque.jpg"><div class="photo-caption">Burlesque</div></a></li>			
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-javier-garcia.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-javier-garcia.jpg"></a><div class="photo-caption">Javier Garcia</div></li>					
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-landland.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-landland.jpg"></a><div class="photo-caption">Landland</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-ellis-latham-brown.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-ellis-latham-brown.jpg"></a><div class="photo-caption">Ellis Latham-Brown</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-methane-studios.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-methane-studios.jpg"></a><div class="photo-caption">Methane Studios</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-silent-giants.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-silent-giants.jpg"></a><div class="photo-caption">Silent Giants</div></li>					
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-ryan-duggan.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-ryan-duggan.jpg"></a><div class="photo-caption">Ryan Duggan</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-tara-mcpherson.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-tara-mcpherson.jpg"></a><div class="photo-caption">Tara McPherson</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-michael-swiatlowski.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-michael-swiatlowski.jpg"></a><div class="photo-caption">Michael Swiatlowski</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-nate-duval.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-nate-duval.jpg"></a><div class="photo-caption">Nate Duval</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-aesthetic-apparatus.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-aesthetic-apparatus.jpg"></a><div class="photo-caption">Aesthetic Apparatus</div></li>		
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-hype-inc.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-hype-inc.jpg"></a><div class="photo-caption">Hyp-Inc</div></li>					
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-alan-hynes.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-alan-hynes.jpg"><div class="photo-caption">Alan Hynes</div></a></li>	
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-daniel-danger.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-daniel-danger.jpg"><div class="photo-caption">Daniel Danger</div></a></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-decoder-ring.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-decoder-ring.jpg"><div class="photo-caption">Decoder Ring</div></a></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-ugly-bogus.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-ugly-bogus.jpg"><div class="photo-caption">Ugly Bogus</div></a></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-shed-labs.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-shed-labs.jpg"><div class="photo-caption">Shed Labs</div></a></li>	
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr12/npr-12-two-arms.jpg"><img class="photo-grid-img" src="_img/npr12/npr-2012-two-arms.jpg"><div class="photo-caption">Two Arms Inc.</div></a></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr12/npr-12-dkng-2.jpg"><img class="photo-grid-img" src="_img/npr12/npr-2012-dkng-2.jpg"></a><div class="photo-caption">DKNG</div></li>					
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr12/npr-12-hatch-show-print.jpg"><img class="photo-grid-img" src="_img/npr12/npr-2012-hatch-show-print.jpg"></a><div class="photo-caption">Hatch Show Print</div></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr12/npr-12-mikey-burton.jpg"><img class="photo-grid-img" src="_img/npr12/npr-2012-mikey-burton.jpg"></a><div class="photo-caption">Mikey Burton</div></li>
			<li class="photo-grid-item"><a class="fancybox" rel="group" href="_img/npr13/npr-13-tooth.jpg"><img class="photo-grid-img" src="_img/npr13/npr-2013-tooth.jpg"></a><div class="photo-caption">Tooth</div></li>
		</ul> <!-- /.photo-grid -->
	</div> <!-- /wrapper -->
</section> <!-- /image-gallery -->				